config/urls.py
from django.contrib import admin
from django.urls import path

from django.urls.conf import include

from .views import entry, home

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('home/', home, name="home"),
    path('', entry, name="entry"),


    path('portfolios/', include("portfolios.urls")),
    path('accounts/', include("accounts.urls")),
    path('data_user/', include("data_user.urls")),
    path('data_market/', include("data_market.urls")),
    path('data_portfolio/', include("data_portfolio.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data_user/urls.py
from django.urls import path

from .views import quickcreate0, quickcreate1, quickcreate2, quickcreate3, quickcreate_menu, register_account

app_name = 'data_user'

urlpatterns = [
    path('quickcreate_menu/<int:id>/', quickcreate_menu, name='quickcreate_menu'),
    path('quickcreate0/<int:id>/', quickcreate0, name='quickcreate0'),
    path('quickcreate1/<int:id>/', quickcreate1, name='quickcreate1'),
    path('quickcreate2/<int:id>/', quickcreate2, name='quickcreate2'),
    path('quickcreate3/<int:id>/', quickcreate3, name='quickcreate3'),
    path('register_account/<int:id>/<str:kind>/', register_account, name='register_account'),
]

portfolios/urls.py
from django.urls import path

from .views import hall, create, open, delete, main

app_name = 'portfolios'

urlpatterns = [

    path('', hall, name='hall'),
    path('create/', create, name='create'),
    path('delete/<int:id>/', delete, name='delete'),
    path('main/<int:id>/', main, name='main'),
    path('open/<int:id>/', open, name='open'),
]

portfolios/models.py
from django.db import models

from django.contrib.auth.models import User


class Portfolio(models.Model):
    # 유저계정 종속
    user = models.ForeignKey(to=User, on_delete=models.PROTECT)
    # 생성 및 마지막 수정 일시
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified_at = models.DateTimeField(auto_now=True)
    # 최근 엑세스 일시
    last_access = models.DateTimeField(auto_now=True)
    # 유저가 설정하는 포트폴리오 이름
    name = models.CharField(
        verbose_name="name",
        max_length=80,
        default="My Portfolio",
    )
    # 메인포트 여부
    is_main = models.BooleanField(default=False)
    # 첫 엑세스 여부
    is_first = models.BooleanField(default=True)
    # 통화 설정
    main_currency = models.CharField(max_length=10, default="KRW")
    is_sub_currency = models.BooleanField(default=False)
    sub_currency = models.CharField(max_length=10, default="USD")
    # 삭제 여부
    is_deleted = models.BooleanField(default=False)

portfolios/views.py
from django.shortcuts import get_object_or_404, redirect, render

from data_portfolio.views import com_dataportfolio_market_preclose, complete_assets, data_portfolio_main, order_chartdata_by_value
from config.views import certification
from visualizing.views import save_main_piechart

from data_portfolio.models import DataPortfolio
from .models import Portfolio

import datetime

from django.contrib.auth.decorators import login_required


@login_required
def hall(request):
    # 유저의 포트폴리오들을 가져와서 랜더
    portfolios = Portfolio.objects.filter(user=request.user, is_deleted=False)
    len_portfolios = len(portfolios)
    context = {
        'portfolios' : portfolios,
        'len_portfolios' : len_portfolios,
    }
    return render(request, 'portfolios/hall.html', context)

@login_required
def create(request):
    # 포트폴리오를 생성
    portfolios = Portfolio.objects.filter(user=request.user, is_deleted=False)
    if len(portfolios) < 2:
        portfolio = Portfolio.objects.create(
            created_at=datetime.datetime.now(),
            user=request.user
        )
        DataPortfolio.objects.create(
            portfolio=portfolio,
            is_main=True
        )
    else:
        return redirect('accounts:logout')
    # 메인포트폴리오가 없으면 생성된 포트폴리오를 메인으로 설정
    main_portfolio = Portfolio.objects.filter(user=request.user, is_main=True, is_deleted=False)
    if len(main_portfolio) == 0:
        portfolio.is_main = True
        portfolio.save()
    return redirect('portfolios:hall')

def delete(request, id):
    # 증명
    portfolio = get_object_or_404(Portfolio, id=id, is_deleted=False)
    certi = certification(request, portfolio)
    if certi == False:
        return redirect('accounts:logout')
    # 삭제
    portfolio.is_deleted=True
    portfolio.save()
    # 
    return redirect('portfolios:hall')

def main(request, id):
    # 증명
    portfolio = get_object_or_404(Portfolio, id=id, is_deleted=False)
    certi = certification(request, portfolio)
    if certi == False:
        return redirect('accounts:logout')
    # 메인이면 메인해제 메인아니면 메인설정하고 다른 메인인 포트 메인해제
    portfolio_is_main = portfolio.is_main
    if portfolio_is_main == True:
        portfolio.is_main=False
        portfolio.save()
    elif portfolio_is_main == False:
        main_portfolios = Portfolio.objects.filter(user=request.user, is_main=True, is_deleted=False)
        if len(main_portfolios) == 1:
            main_portfolio = get_object_or_404(Portfolio, user=request.user, is_main=True, is_deleted=False)
            main_portfolio.is_main=False
            main_portfolio.save()
        portfolio.is_main=True
        portfolio.save()
    return redirect('portfolios:hall')

@login_required
def open(request, id):
    # 증명
    portfolio = get_object_or_404(Portfolio, id=id, is_deleted=False)
    certi = certification(request, portfolio)
    if certi == False:
        return redirect('accounts:logout')
    # com asset
    now = datetime.datetime.now()
    is_com = complete_assets(id, now)
    if is_com == False:
        return redirect('fail')
    # data 포트폴리오 수정하기
    dataportfolio = data_portfolio_main(portfolio)
    if dataportfolio == False:
        return redirect('fail')
    # 마켓 테이터 이용하여 차트 데이터 만들기
    list_list_chartdata = com_dataportfolio_market_preclose(dataportfolio)
    if list_list_chartdata == False:
        return redirect('fail')
    # 차트 데이터 정렬하기
    list_chartdata_stockthing = list_list_chartdata[0]
    list_chartdata_crypto = list_list_chartdata[1]
    list_chartdata_cash = list_list_chartdata[2]
    list_chartdata_saving = list_list_chartdata[3]
    ordered_chartdata_stockthing = order_chartdata_by_value(list_chartdata_stockthing)
    if ordered_chartdata_stockthing == False:
        return redirect('fail')
    ordered_chartdata_crypto = order_chartdata_by_value(list_chartdata_crypto)
    if ordered_chartdata_crypto == False:
        return redirect('fail')
    ordered_chartdata_cash = order_chartdata_by_value(list_chartdata_cash)
    if ordered_chartdata_cash == False:
        return redirect('fail')
    ordered_chartdata_saving = order_chartdata_by_value(list_chartdata_saving)
    if ordered_chartdata_saving == False:
        return redirect('fail')
    # 메인 파이차트 저장하기
    value_list = ordered_chartdata_stockthing[0]
    label_list = ordered_chartdata_stockthing[1]
    naming = 'stockthing'
    chartmaker = save_main_piechart(value_list, label_list, id, naming)
    if chartmaker == False:
        return redirect('fail')
    value_list = ordered_chartdata_crypto[0]
    label_list = ordered_chartdata_crypto[1]
    naming = 'crypto'
    chartmaker = save_main_piechart(value_list, label_list, id, naming)
    if chartmaker == False:
        return redirect('fail')
    value_list = ordered_chartdata_cash[0]
    label_list = ordered_chartdata_cash[1]
    naming = 'cash'
    chartmaker = save_main_piechart(value_list, label_list, id, naming)
    if chartmaker == False:
        return redirect('fail')
    value_list = ordered_chartdata_saving[0]
    label_list = ordered_chartdata_saving[1]
    naming = 'saving'
    chartmaker = save_main_piechart(value_list, label_list, id, naming)
    if chartmaker == False:
        return redirect('fail')
    value_list = [dataportfolio.stockthing] + [dataportfolio.crypto] + ordered_chartdata_cash[0]
    label_list = ['stock'] + ['crypto'] + ordered_chartdata_cash[1]
    naming = 'stock_crypto_cash'
    chartmaker = save_main_piechart(value_list, label_list, id, naming)
    if chartmaker == False:
        return redirect('fail')
    value_list = [dataportfolio.stockthing] + [dataportfolio.crypto] + [dataportfolio.saving] + [dataportfolio.cash]
    label_list = ['stock'] + ['crypto'] + ['saving'] + ['cash']
    naming = 'stock_crypto_saving_cash'
    chartmaker = save_main_piechart(value_list, label_list, id, naming)
    if chartmaker == False:
        return redirect('fail')

    context = {
        'portfolio_id' : id,
    }
    return render(request, 'portfolios/main.html', context)

    

templates/portfolios/hall.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

{% endblock title %}


{% block content %}

<div class="card-group">
{% for portfolio in portfolios %}
    <div class="card" style="max-width: 21rem; background-color: #212121;" >
        {% if portfolio.is_main == True %}
        <a href="{% url 'portfolios:open' portfolio.id %}">
        <img class="card-img-top" src="{% static "/img/mainbook.png" %}" alt="...">
        </a>
        {% else %}
        <a href="{% url 'portfolios:open' portfolio.id %}">
        <img class="card-img-top" src="{% static "/img/book.png" %}" alt="...">
        </a>
        {% endif %}
        <div class="card-header">
        <a href="{% url 'portfolios:open' portfolio.id %}">{{portfolio.name}}</a>
        </div>
        <div class="card-body">
            <a href="{% url 'data_user:quickcreate_menu' portfolio.id %}">Quick Create</a>
        </div>
        <div class="card-footer">
            <a href="{% url 'portfolios:delete' portfolio.id %}">삭제하기</a>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {% if portfolio.is_main == True %}
            <a href="{% url 'portfolios:main' portfolio.id %}">(main해제)</a>
            {% else %}
            <a href="{% url 'portfolios:main' portfolio.id %}">(main으로설정)</a>
            {% endif %}
        </div>
    </div>
{% endfor %}
    <div class="card" style="max-width: 21rem; background-color: #212121;">
        {% if len_portfolios > 1 %}
            <img class="card-img-top" src="{% static "/img/lock.png" %}" alt="...">
        {% else %}
            <a href="{% url 'portfolios:create' %}" class="card-img-top">
            <img class="card-img-top" src="{% static "/img/plus.png" %}" alt="Card image cap">
            </a>
        {% endif %}
    </div>
</div>

{% endblock content %}

templates/portfolios/main.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

{% endblock title %}


{% block content %}



<div class="card-group">
    <div class="card" style="max-width: 18rem; background-color: #000000;">
        <img class="card-img-top" src="{% get_static_prefix %}img/visualizing/{{portfolio_id}}_main_stock_crypto_saving_cash.png" alt="Card image cap">
    </div>

    <div class="card" style="max-width: 30rem; background-color: #000000;">
        <img class="card-img-top" src="{% get_static_prefix %}img/visualizing/{{portfolio_id}}_main_stock_crypto_cash.png" alt="Card image cap">
    </div>

    <div class="card" style="max-width: 18rem; background-color: #000000;">
        <img class="card-img-top" src="{% get_static_prefix %}img/visualizing/{{portfolio_id}}_main_crypto.png" alt="Card image cap">
    </div>
</div>


<div class="card-group">
    <div class="card" style="max-width: 14rem; background-color: #000000;">
        <img class="card-img-top" src="{% get_static_prefix %}img/visualizing/{{portfolio_id}}_main_saving.png" alt="Card image cap">
    </div>

    <div class="card" style="max-width: 18rem; background-color: #000000;">
        <img class="card-img-top" src="{% get_static_prefix %}img/visualizing/{{portfolio_id}}_main_cash.png" alt="Card image cap">
    </div>

    <div class="card" style="max-width: 50rem; background-color: #000000;">
        <img class="card-img-top" src="{% get_static_prefix %}img/visualizing/{{portfolio_id}}_main_stockthing.png" alt="Card image cap">
    </div>
</div>





{% endblock content %}