config/urls.py
from django.contrib import admin
from django.urls import path

from django.urls.conf import include

from .views import entry, home

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('home/', home, name="home"),
    path('', entry, name="entry"),


    path('portfolios/', include("portfolios.urls")),
    path('accounts/', include("accounts.urls")),
    path('data_user/', include("data_user.urls")),
    path('data_market/', include("data_market.urls")),
    path('data_portfolio/', include("data_portfolio.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data_user/urls.py
from django.urls import path

from .views import quickcreate0, quickcreate1, quickcreate2, quickcreate3, quickcreate_menu, register_account

app_name = 'data_user'

urlpatterns = [
    path('quickcreate_menu/<int:id>/', quickcreate_menu, name='quickcreate_menu'),
    path('quickcreate0/<int:id>/', quickcreate0, name='quickcreate0'),
    path('quickcreate1/<int:id>/', quickcreate1, name='quickcreate1'),
    path('quickcreate2/<int:id>/', quickcreate2, name='quickcreate2'),
    path('quickcreate3/<int:id>/', quickcreate3, name='quickcreate3'),
    path('register_account/<int:id>/<str:kind>/', register_account, name='register_account'),
]

portfolios/urls.py
from django.urls import path

from .views import hall, create, open, delete, main

app_name = 'portfolios'

urlpatterns = [

    path('', hall, name='hall'),
    path('create/', create, name='create'),
    path('delete/<int:id>/', delete, name='delete'),
    path('main/<int:id>/', main, name='main'),
    path('open/<int:id>/', open, name='open'),
]

data_user/models.py
from django.db import models

from data_support.models import AssetFormat
from portfolios.models import Portfolio


class PortfoliosAccount(models.Model):
    # 특정 Portfolio 종속
    portfolio = models.ForeignKey(to=Portfolio, on_delete=models.PROTECT)
    # 생성 및 마지막 수정 일시
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified_at = models.DateTimeField(auto_now=True)
    # 최근 엑세시 일시
    last_access = models.DateTimeField(auto_now=True)
    # 필터
    a = models.BooleanField(default=False, help_text="stocks, etf,,, exchange traded financial instruments")
    b = models.BooleanField(default=False, help_text="crypto")
    c = models.BooleanField(default=False, help_text="cash")
    s = models.BooleanField(default=False, help_text="savings")
    p = models.BooleanField(default=False, help_text="pension, retire, insurance, annuity,,,")
    r = models.BooleanField(default=False, help_text="real estate")
    z = models.BooleanField(default=False, help_text="painting, goods etc")
    # 대표이름
    title = models.CharField(max_length=30, default="")
    # account 오리지널 이름
    name = models.CharField(max_length=100)
    # 유저가 설정한 이름
    nickname = models.CharField(max_length=50)
    # 유저가 기입한 주석
    remark = models.TextField()



### 참고 ###
# ## classi = dataportfolio 에서 연산할떄 분류(유저에게 보여주는 분류)
# a : 주식
# b : 크립토
# c : 통화
# d : 통화 기반 saving
classi_list = ['a', 'b', 'c', 'd']

# !!! 이 모델은 절대로 유저가 직접 접근할 수 없어야 합니다 !!!
class AccountsAsset(models.Model):
    # 특정 account 종속
    account = models.ForeignKey(to=PortfoliosAccount, on_delete=models.PROTECT)
    # 포멧 종속
    format = models.ForeignKey(to=AssetFormat, on_delete=models.PROTECT)
    # dataportfolio 분류
    classi = models.CharField(max_length=50)
    # 생성 및 마지막 수정 일시
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified_at = models.DateTimeField(auto_now=True)
    # 최근 엑세시 일시
    last_access = models.DateTimeField(auto_now=True)
    # asset 코드(특정할 수 있는 고유한 코드)
    code = models.CharField(max_length=50)
    # asset title(대표하는)
    title = models.CharField(max_length=100)
    # asset 이름
    name = models.CharField(max_length=100)
    # asset 속성(필요한 asset에만 사용)
    attribute = models.CharField(max_length=100)
    # asset 수량
    amount = models.FloatField(default=0)
    # portfolio 종속
    portfolio = models.ForeignKey(to=Portfolio, on_delete=models.PROTECT)


DEFAULT = 'DF'
QUICK = 'QK'
TRADE = 'TD'
INOUT = 'IO'
INSIDE = 'IS'
USER = 'US'
INTEREST = 'IR'
DIVIDEND = 'DD'
RENT = 'RT'
PAY = 'PY'

action_rabels = [
    (DEFAULT, 'default'),
    (QUICK, '빠른생성'),
    (TRADE, '거래'),
    (INOUT, '입출'),
    (INSIDE, '내부거래'),
    (USER, '수정'),
    (INTEREST, '이자'),
    (DIVIDEND, '배당'),
    (RENT, '월세'),
    (PAY, '급여'),
]

class AssetsAction(models.Model):
    # 생성 및 마지막 수정 일시
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified_at = models.DateTimeField(auto_now=True)
    # 실제 액션 일시
    action_time = models.DateTimeField(auto_now_add=True)
    # buy/sell asset 종속
    asset_buy = models.ForeignKey(to=AccountsAsset, null=True, on_delete=models.PROTECT, related_name='action_asset_buy')
    asset_sell = models.ForeignKey(to=AccountsAsset, null=True, on_delete=models.PROTECT, related_name='action_asset_sell')
    # buy/sell 수량
    amount_buy = models.FloatField(default=0)
    amount_sell = models.FloatField(default=0)
    # 라벨링
    rabel = models.CharField(
        max_length=2,
        choices=action_rabels,
        default=DEFAULT,
    )
    # 특정 account 종속
    account_buy = models.ForeignKey(to=PortfoliosAccount, null=True, on_delete=models.PROTECT, related_name='action_account_buy')
    account_sell = models.ForeignKey(to=PortfoliosAccount, null=True, on_delete=models.PROTECT, related_name='action_account_sell')
    # portfolio 종속
    portfolio = models.ForeignKey(to=Portfolio, on_delete=models.PROTECT)

data_user/views.py
from django.shortcuts import get_object_or_404, redirect, render

from django.contrib.auth.decorators import login_required

from data_market.models import CryptoUSD, ExchangeRate, TickerSymbol
from .models import AccountsAsset, AssetsAction, PortfoliosAccount
from portfolios.models import Portfolio
from data_support.models import AssetFormat, FinancialAccountsTitle

from config.views import certification
from data_market.views import data_cryptousd, data_tickersymbol


@login_required
def quickcreate_menu(request, id):
    # 증명
    portfolio = get_object_or_404(Portfolio, id=id, is_deleted=False)
    certi = certification(request, portfolio)
    if certi == False:
        return redirect('accounts:logout')
    # 포트id 가지고 랜더
    context = {
        'id_portfolio' : id,
    }
    return render(request, 'data_user/quickcreate_menu.html', context)

@login_required
def quickcreate0(request, id):
    # 증명
    portfolio = get_object_or_404(Portfolio, id=id, is_deleted=False)
    certi = certification(request, portfolio)
    if certi == False:
        return redirect('accounts:logout')
    # 메써드가 포스트이고 작성이 완료가 안됬으면
    if request.method == "POST" and request.POST['complete'] == "n":
        code = request.POST['code']
        code = code.upper()
        if len(code) == 6 and code.isdigit() == True:
            code = code + ".KS"
        data_symbol = data_tickersymbol(code)
        if data_symbol == False:
            list_for_create = []
            try:
                len_list = int(request.POST['len_list'])
                for i in range(len_list):
                    account_id = request.POST[f'account_id{i}']
                    ticker = request.POST[f'ticker{i}']
                    ticker = ticker.upper()
                    shortName = request.POST[f'shortName{i}']
                    amount = request.POST[f'amount{i}']
                    dic = {}
                    dic['account_id'] = account_id
                    dic['ticker'] = ticker
                    dic['shortName'] = shortName
                    dic['amount'] = amount
                    list_for_create = list_for_create + [dic]
            except:
                pass
            # 오류 메세지를 context에 추가하여 템플릿 랜더하기
            # 포트폴리오 종속 어카운트와 포트id를 context에 담기
            accounts = PortfoliosAccount.objects.filter(portfolio=portfolio, a=True)
            tickersymbols = TickerSymbol.objects.all()

            try:
                context = {
                    'id_portfolio' : id,
                    'accounts' : accounts,
                    'kind' : 'a',
                    'tickersymbols' : tickersymbols,
                    'error': "symbol을 찾을수 없습니다.",
                    'len_list' : len_list,
                    'list_for_create' : list_for_create,
                }
            except:
                context = {
                    'id_portfolio' : id,
                    'accounts' : accounts,
                    'kind' : 'a',
                    'tickersymbols' : tickersymbols,
                    'error': "symbol을 찾을수 없습니다.",
                    'list_for_create' : list_for_create,
                }

            # 작성 템플릿 랜더
            return render(request, 'data_user/quickcreate0.html', context)
        ##### 있거나 만들어왔으면 생성할 모델들의 재료들을 기록해두고 다시 랜더하기
        list_for_create = []
        try:
            len_list = int(request.POST['len_list'])
            for i in range(len_list):
                account_id = request.POST[f'account_id{i}']
                ticker = request.POST[f'ticker{i}']
                ticker = ticker.upper()
                shortName = request.POST[f'shortName{i}']
                amount = request.POST[f'amount{i}']
                dic = {}
                dic['account_id'] = account_id
                dic['ticker'] = ticker
                dic['shortName'] = shortName
                dic['amount'] = amount
                list_for_create = list_for_create + [dic]
        except:
            pass
        account_id = request.POST['account']
        selected_maker = request.POST['account']
        tickersymbol = get_object_or_404(TickerSymbol, symbol=code)
        shortName = tickersymbol.shortName
        amount = request.POST['amount']
        dic = {}
        dic['account_id'] = account_id
        dic['ticker'] = code
        dic['shortName'] = shortName
        dic['amount'] = amount
        list_for_create = list_for_create + [dic]
        len_list = len(list_for_create)
        ##### context 만들고 랜더
        ### context 만들기
        # 포트폴리오 종속 어카운트와 포트id를 context에 담기
        accounts = PortfoliosAccount.objects.filter(portfolio=portfolio, a=True)
        tickersymbols = TickerSymbol.objects.all()
        context = {
            'id_portfolio' : id,
            'accounts' : accounts,
            'kind' : 'a',
            'tickersymbols' : tickersymbols,
            'len_list' : len_list,
            'list_for_create' : list_for_create,
            'selected_maker' : selected_maker,
        }
        ### 랜더
        return render(request, 'data_user/quickcreate0.html', context)
    # 메써드가 포스트 이고 작성이 완료됬으면 asset 과 action 만들기
    elif request.method == "POST" and request.POST['complete'] == "y":
        len_list = int(request.POST['len_list'])
        for i in range(len_list):
            account_id = request.POST[f'account_id{i}']
            ticker = request.POST[f'ticker{i}']
            ticker = ticker.upper()
            amount = request.POST[f'amount{i}']
            # symbol모델에서 찾아오기
            tickersymbol = get_object_or_404(TickerSymbol, symbol=ticker)
            ##### asset 만들기
            account = get_object_or_404(PortfoliosAccount, id=account_id)
            code = tickersymbol.symbol
            name = tickersymbol.longName
            format = get_object_or_404(AssetFormat, code='aa')
            # 계좌에 동일역할 asset이 이미 있는지 확인
            check = AccountsAsset.objects.filter(account=account, format=format, code=code)
            # 없을떄만 생성
            if len(check) == 0:
                AccountsAsset.objects.create(
                    account=account,
                    format=format,
                    classi='a',
                    code=code,
                    name=name,
                    portfolio=portfolio
                )
            # action 만들기
            asset = get_object_or_404(AccountsAsset, account=account, format=format, code=code)
            amount_buy = amount
            AssetsAction.objects.create(
                asset_buy=asset,
                amount_buy=amount_buy,
                rabel='IO',
                account_buy=account,
                portfolio=portfolio
            )
        # 
        return redirect('data_user:quickcreate0', id)
    # 머써드가 포스트가 아니면
    else:
        # 포트폴리오 종속 어카운트와 포트id를 context에 담기
        accounts = PortfoliosAccount.objects.filter(portfolio=portfolio, a=True)
        tickersymbols = TickerSymbol.objects.all()
        context = {
            'id_portfolio' : id,
            'accounts' : accounts,
            'kind' : 'a',
            'tickersymbols' : tickersymbols,
        }
        # 작성 템플릿 랜더
        return render(request, 'data_user/quickcreate0.html', context)


def quickcreate1(request, id):
    # 증명
    portfolio = get_object_or_404(Portfolio, id=id, is_deleted=False)
    certi = certification(request, portfolio)
    if certi == False:
        return redirect('accounts:logout')
    # 메써드가 포스트이고 작성이 완료가 안됬으면
    if request.method == "POST" and request.POST['complete'] == "n":
        symbol = request.POST['symbol']
        symbol = symbol.upper()
        if symbol[-4:] != '-USD':
            symbol = symbol + '-USD'
        # 입력한 symbol 가져와서 CryptoUSD 만들어보기
        data_symbol = data_cryptousd(symbol)
        # 없고 못만들었으면
        if data_symbol == False:
            # 지금까지 입력받은 입력리스트 받아오기
            list_for_create = []
            try:
                len_list = int(request.POST['len_list'])
                for i in range(len_list):
                    account_id = request.POST[f'account_id{i}']
                    ticker = request.POST[f'ticker{i}']
                    ticker = ticker.upper()
                    shortName = request.POST[f'shortName{i}']
                    amount = request.POST[f'amount{i}']
                    dic = {}
                    dic['account_id'] = account_id
                    dic['ticker'] = ticker
                    dic['shortName'] = shortName
                    dic['amount'] = amount
                    list_for_create = list_for_create + [dic]
            # 없으면 예외처리해서 패스
            except:
                pass
            # 오류 메세지를 context에 추가하여 템플릿 랜더하기
            accounts = PortfoliosAccount.objects.filter(portfolio=portfolio, b=True)
            cryptousds = CryptoUSD.objects.all()

            try:
                context = {
                    'id_portfolio' : id,
                    'accounts' : accounts,
                    'kind' : 'b',
                    'cryptousds' : cryptousds,
                    'error': "symbol을 찾을수 없습니다.",
                    'len_list' : len_list,
                    'list_for_create' : list_for_create,
                }
            except:
                context = {
                    'id_portfolio' : id,
                    'accounts' : accounts,
                    'kind' : 'b',
                    'cryptousds' : cryptousds,
                    'error': "symbol을 찾을수 없습니다.",
                    'list_for_create' : list_for_create,
                }

            # 작성 템플릿 랜더
            return render(request, 'data_user/quickcreate1.html', context)
        ##### 있거나 만들어왔으면 생성할 모델들의 재료들을 기록해두고 다시 랜더하기
        list_for_create = []
        try:
            len_list = int(request.POST['len_list'])
            for i in range(len_list):
                account_id = request.POST[f'account_id{i}']
                ticker = request.POST[f'ticker{i}']
                ticker = ticker.upper()
                shortName = request.POST[f'shortName{i}']

templates/data_user/quickcreate1.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}


{% block content %}

{% if error %}
{{ error }}
{% endif %}

<a href="{% url 'data_user:quickcreate_menu' id_portfolio %}">빠른생성메뉴로가기</a>

<hr>

<br>

<form method="POST" action="">
  {% csrf_token %}
  <input type="hidden" name="complete" value="n">
  <div class="form-group">
    <label for="">select account</label>
    <select name='account' style="width:400px" required class="form-control" id="">
      {% for account in accounts %}
        {% if selected_maker == account.id|slugify %}
        <option selected value="{{account.id}}">{{account.title}} {{account.nickname}}</option>
        {% else %}
        <option value="{{account.id}}">{{account.title}} {{account.nickname}}</option>
        {% endif %}
      {% endfor %}
    </select>

    계좌가 없으면 등록해주세요
    <a href="{% url 'data_user:register_account' id_portfolio kind %}" class="btn btn-primary">새로운 account 등록하러 가기</a>
  </div>

  <br>

  <div class="form-group">
    {% if error %}
    {{ error }}
    {% endif %}
    <label for="">Symbol 검색</label>
    <input type="text" name="symbol" style="width:400px" class="form-control" list="symbols" id="">

    <datalist id="symbols">
    {% for cryptousd in cryptousds %}
    <option value="{{cryptousd.symbol}}">{{cryptousd.shortName}}</option>
    {% endfor %}
    </datalist>
  </div>

  <br>

  <div class="form-group">
    <label for="">수량</label>
    <input type="number" step=any style="width:400px" name="amount" class="form-control" id="">
  </div>

  <br>
  {% if len_list %}
    <input type="hidden" name="len_list" value="{{len_list}}">
      
    {% for dic in list_for_create %}
      <input type="hidden" name="account_id{{forloop.counter0}}" value="{{dic.account_id}}">
      <input type="hidden" name="ticker{{forloop.counter0}}" value="{{dic.ticker}}">
      <input type="hidden" name="shortName{{forloop.counter0}}" value="{{dic.shortName}}">
      <input type="hidden" name="amount{{forloop.counter0}}" value="{{dic.amount}}">
    {% endfor %}

  {% endif %}

  <input type="submit" value="register">
</form>

<br>

<hr>
{% regroup list_for_create|dictsort:"account_id" by account_id as account_list %}
{% for account_id in account_list %}
<div class="card" style="max-width: 30rem;">
  <div class="card-header">
  {% for account in accounts %}
  {% if account.id|slugify == account_id.grouper %}
  {{account.title}} {{account.nickname}}
  {% endif %}
  {% endfor %}
  </div>
  <ul class="list-group list-group-flush">
    {% for ticker in account_id.list %}
    <li class="list-group-item">{{ticker.ticker|upper}} 
      <span>{{ticker.shortName}}</span> 
      <span>{{ticker.amount}}</span>
     </li>
    {% endfor %}
  </ul>
</div>
<br>
{% endfor %}


{% if len_list %}
<form action="" method="POST">
{% csrf_token %}
  <input type="hidden" name="complete" value="y">
  <input type="hidden" name="len_list" value="{{len_list}}">
  {% for dic in list_for_create %}
    <input type="hidden" name="account_id{{forloop.counter0}}" value="{{dic.account_id}}">
    <input type="hidden" name="ticker{{forloop.counter0}}" value="{{dic.ticker}}">
    <input type="hidden" name="amount{{forloop.counter0}}" value="{{dic.amount}}">
  {% endfor %}
  <input type="submit" value="complete">
  <a href="{% url 'data_user:quickcreate1' id_portfolio %}" class="btn btn-primary">reset</a>
{% endif %}
</form>
<a href="{% url 'data_user:quickcreate_menu' id_portfolio %}">빠른생성메뉴로나가기</a>
<br>

<hr>

{% endblock content %}

templates/data_user/quickcreate2.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}


{% block content %}

{% if error %}
{{ error }}
{% endif %}

<a href="{% url 'data_user:quickcreate_menu' id_portfolio %}">빠른생성메뉴로가기</a>

<hr>

<br>

<form method="POST" action="">
  {% csrf_token %}
  <input type="hidden" name="complete" value="n">
  <div class="form-group">
    <label for="">select account</label>
    <select name='account' style="width:400px" required class="form-control" id="">
      {% for account in accounts %}
        {% if selected_maker == account.id|slugify %}
        <option selected value="{{account.id}}">{{account.title}} {{account.nickname}}</option>
        {% else %}
        <option value="{{account.id}}">{{account.title}} {{account.nickname}}</option>
        {% endif %}
      {% endfor %}
    </select>

    계좌가 없으면 등록해주세요
    <a href="{% url 'data_user:register_account' id_portfolio kind %}" class="btn btn-primary">새로운 account 등록하러 가기</a>
  </div>

  <br>

  <div class="form-group">
    {% if error %}
    {{ error }}
    {% endif %}
    <label for="">Currency</label>
    <select name='symbol' style="width:400px" required class="form-control" id="">
      {% for exchangerate in exchangerates %}
      <option value="{{exchangerate.currency}}">{{exchangerate.currency_name}}</option>
      {% endfor %}
    </select>
  </div>

  <br>

  <div class="form-group">
    <label for="">금액</label>
    <input type="number" style="width:400px" step=any name="amount" class="form-control" id="">
  </div>

  <br>
  {% if len_list %}
    <input type="hidden" name="len_list" value="{{len_list}}">
      
    {% for dic in list_for_create %}
      <input type="hidden" name="account_id{{forloop.counter0}}" value="{{dic.account_id}}">
      <input type="hidden" name="ticker{{forloop.counter0}}" value="{{dic.ticker}}">
      <input type="hidden" name="shortName{{forloop.counter0}}" value="{{dic.shortName}}">
      <input type="hidden" name="amount{{forloop.counter0}}" value="{{dic.amount}}">
    {% endfor %}

  {% endif %}

  <input type="submit" value="register">
</form>

<br>

<hr>
{% regroup list_for_create|dictsort:"account_id" by account_id as account_list %}
{% for account_id in account_list %}
<div class="card" style="max-width: 30rem;">
  <div class="card-header">
  {% for account in accounts %}
  {% if account.id|slugify == account_id.grouper %}
  {{account.title}} {{account.nickname}}
  {% endif %}
  {% endfor %}
  </div>
  <ul class="list-group list-group-flush">
    {% for ticker in account_id.list %}
    <li class="list-group-item">{{ticker.ticker|upper}} 
      <span>{{ticker.shortName}}</span> 
      <span>{{ticker.amount}}</span>
     </li>
    {% endfor %}
  </ul>
</div>
<br>
{% endfor %}


{% if len_list %}
<form action="" method="POST">
{% csrf_token %}
  <input type="hidden" name="complete" value="y">
  <input type="hidden" name="len_list" value="{{len_list}}">
  {% for dic in list_for_create %}
    <input type="hidden" name="account_id{{forloop.counter0}}" value="{{dic.account_id}}">
    <input type="hidden" name="ticker{{forloop.counter0}}" value="{{dic.ticker}}">
    <input type="hidden" name="amount{{forloop.counter0}}" value="{{dic.amount}}">
  {% endfor %}
  <input type="submit" value="complete">
  <a href="{% url 'data_user:quickcreate2' id_portfolio %}" class="btn btn-primary">reset</a>
{% endif %}
</form>
<a href="{% url 'data_user:quickcreate_menu' id_portfolio %}">빠른생성메뉴로나가기</a>
<br>

<hr>

{% endblock content %}

templates/data_user/quickcreate_menu.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}


{% block content %}
<div style="text-align : center;">
<h1>간편 생성 메뉴</h1>



<hr>
<br>
<br>
<a href="{% url 'data_user:quickcreate0' id_portfolio %}" class="btn btn-primary">주식/ETF등(상장금융상품)</a>
<br>
<br>
<a href="{% url 'data_user:quickcreate1' id_portfolio %}" class="btn btn-primary">암호화폐</a>
<br>
<br>
<a href="{% url 'data_user:quickcreate2' id_portfolio %}" class="btn btn-primary">현금/현금성자산(자유입출예금 등)</a>
<br>
<br>
<a href="{% url 'data_user:quickcreate3' id_portfolio %}" class="btn btn-primary">예금/적금</a>
<br>
<br>
<a href="{% url 'data_user:quickcreate1' id_portfolio %}" class="btn btn-primary">연금/보험</a>
<br>
<br>
<a href="{% url 'data_user:quickcreate1' id_portfolio %}" class="btn btn-primary">부동산</a>
<br>
<br>
<a href="{% url 'data_user:quickcreate1' id_portfolio %}" class="btn btn-primary">기타자산</a>
<br>
<br>
<a href="{% url 'data_user:quickcreate1' id_portfolio %}" class="btn btn-primary">대출</a>
<br>
<br>
<hr>
<a href="{% url 'portfolios:open' id_portfolio %}" class="btn btn-primary">빠른생성마치기</a>

</div>
{% endblock content %}

templates/data_user/quickcreatemenu.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}


{% block content %}

<h1>빠른생성메뉴</h1>

<hr>
<br>
<br>
<a href="{% url 'data_user:quickcreate1' id_portfolio %}" class="btn btn-primary">주식/ETF(상장금융상품)</a>
<br>
<br>
<a href="{% url 'data_user:quickcreate1' id_portfolio %}" class="btn btn-primary">암호화폐</a>
<br>
<br>
<a href="{% url 'data_user:quickcreate1' id_portfolio %}" class="btn btn-primary">현금/현금성자산(자유입출예금)</a>
<br>
<br>
<a href="{% url 'data_user:quickcreate1' id_portfolio %}" class="btn btn-primary">예금/적금</a>
<br>
<br>
<a href="{% url 'data_user:quickcreate1' id_portfolio %}" class="btn btn-primary">퇴직금/연금/보험</a>
<br>
<br>
<hr>
<a href="{% url 'portfolios:open' id_portfolio %}" class="btn btn-primary">빠른생성종료</a>

{% endblock content %}

templates/data_user/register_account.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}


{% block content %}

<a href="{% url 'data_user:quickcreate_menu' id_portfolio %}">빠른생성메뉴로가기</a>

<hr>

<br>

<form method="POST" action="">
  {% csrf_token %}
  <div class="form-group">
    <label for="">없으면 직접 입력해주세요. 리스트에 포함시키겠습니다.</label>
    <input type="text" name="title" style="width:400px" class="form-control" list="titles" id="">
    <datalist id="titles">
    {% for title in titles %}
    <option>{{title.title}}</option>
    {% endfor %}
    </datalist>
  </div>

  <div >
    <label for="">이 account의 별칭을 지어주세요</label><br>
    <input type="text" name="nickname" value="">
  </div>

  <input type="submit" value="register">
</form>

<br>

<hr>

{% endblock content %}