accounts/urls.py
from django.urls import path

from .views import signup, login, logout, login_next

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name="signup"),
    path('login/', login, name="login"),
    path('login_next/', login_next, name="login_next"),
    path('logout/', logout, name="logout"),
]

config/urls.py
from django.contrib import admin
from django.urls import path

from django.urls.conf import include

from .views import entry, home

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('home/', home, name="home"),
    path('', entry, name="entry"),


    path('portfolios/', include("portfolios.urls")),
    path('accounts/', include("accounts.urls")),
    path('data_user/', include("data_user.urls")),
    path('data_market/', include("data_market.urls")),
    path('data_portfolio/', include("data_portfolio.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolios/urls.py
from django.urls import path

from .views import hall, create, open, delete, main

app_name = 'portfolios'

urlpatterns = [

    path('', hall, name='hall'),
    path('create/', create, name='create'),
    path('delete/<int:id>/', delete, name='delete'),
    path('main/<int:id>/', main, name='main'),
    path('open/<int:id>/', open, name='open'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        Lapiki | {% block title %}
        {% endblock title %}
    </title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body style="background-color:#000000">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #000000;">
            <div class="container-fluid">
            {% if home != 'y' %}
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static "/img/logo.png" %}" width="100" alt="">
                </a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            {{user.username}} 님</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'portfolios:hall' %}">포트폴리오</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'accounts:logout' %}">로그아웃</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a href="{% url 'accounts:login' %}">로그인</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'accounts:signup' %}">회원가입</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    {% block content %}
    {% endblock content %}

</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

{% endblock title %}


{% block content %}

<div>
<br><br><br><br><br><br><br><br><br><br><br>
</div>

<div style="text-align : center;">
<img src="{% static "/img/logo.png" %}" width="500" alt="">
</div>

{% endblock content %}